runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: cravely
  MASTER_KEY: 22142e23-57a2-4c24-b14e-d516a94aaeee
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  CLOUD_CODE_MAIN: cloud/main.js
